DROP TABLE IF EXISTS USER;

CREATE TABLE USER(USER_ID INTEGER PRIMARY KEY);

INSERT INTO USER(USER_ID) VALUES(1);
INSERT INTO USER(USER_ID) VALUES(2);
INSERT INTO USER(USER_ID) VALUES(3);
INSERT INTO USER(USER_ID) VALUES(4);

