DROP TABLE IF EXISTS USER;

CREATE TABLE USER(USER_ID INTEGER PRIMARY KEY);

INSERT INTO USER(USER_ID) VALUES(1);
INSERT INTO USER(USER_ID) VALUES(2);
INSERT INTO USER(USER_ID) VALUES(3);
INSERT INTO USER(USER_ID) VALUES(4);

DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE INSTRUMENT(ID TEXT PRIMARY KEY, 
		SYMBOL TEXT, 
		CURRENTPRICE REAL, 
		DESCRIPTION TEXT, 
		INSTRUMENT_TYPE TEXT,
		FUNDNM TEXT,
		FUNDHOUSE TEXT,
		NOOFUNITS REAL,
		UNITPRICE REAL,
		DIVOPTION TEXT
		);